name: Find Latest Text File
# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
      name: Find the latest File
      runs-on: ubuntu-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout the code
          uses: actions/checkout@v3

        # Runs a set of commands using the runners shell
        - name: Run a multi-line script
          run: |
            file=$(ls -Art *.txt | head -n1)
            echo "$file"

