# name: Find Latest Text File
# # Controls when the workflow will run
# on:
#   push:
#     branches: [ "main" ]
# jobs:
#   deploy:
#       name: Find the latest File
#       runs-on: ubuntu-latest
#       # Steps represent a sequence of tasks that will be executed as part of the job
#       steps:
#         # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#         - name: Checkout the code
#           uses: actions/checkout@v3

#         # Runs a set of commands using the runners shell
#         - name: Run a multi-line script
#           run: |
#             file=$(ls -Art *.txt | head -n1)
#             echo "$file"
name: push-develop
on: [push]
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          output: 'json'
          fileOutput: 'json'
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          
          
          TEMP='${{ steps.file_changes.outputs.files_modified}}'
          echo "$TEMP"
          newFile=$(sed -E 's|.*(test)|\1|'<<<"$TEMP")
          echo "$newFile" > File.txt
          value=$(<File.txt)
          echo "$value"
       - name: Update File
         run: echo "$newFile" > File.txt && value=$(<File.txt) && echo "$value"
          
          
          
# name: push-develop
# on: [push]
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - id: file_changes
#         uses: trilom/file-changes-action@v1.2.3
#         with:
#           output: ','
#           fileOutput: ','
#       - name: test
#         run: |
#           cat $HOME/files.csv